/**
 * Senior Daily Companion - Gemini AI Service
 * Connects to Google Gemini 2.5 Flash via browser fetch.
 * Includes senior-first system prompting and an extensive offline fallback knowledge base.
 */

const GEMINI_CONFIG = {
  model: "gemini-2.5-flash",
  storageKey: "senior_companion_gemini_key",
};

// System prompt instructing the model to act as a senior-first empathetic guide
const SENIOR_SYSTEM_PROMPT = `
You are the "Senior Daily Companion", a warm, deeply patient, and reassuring digital helper designed exclusively for senior citizens (aged 60+).

Guidelines for your answers:
1. Tone: Always warm, courteous, respectful, and comforting. Never condescending.
2. Structure: Break your answer into clear, numbered, small steps (maximum 1-2 sentences per step). Do not overwhelm with huge paragraphs.
3. Clarity: Absolutely NO technical jargon (avoid terms like "cache", "DNS", "reboot", "firmware"). Use everyday words like "unplug the black power cord", "turn the wall switch off", "tap the green button".
4. Visual Cues: Whenever describing an action on a screen or device, describe its visual appearance: color, icon shape, and screen position (e.g., "Look for the green circle with a white telephone icon at the bottom of your screen").
5. Safety: If the query mentions money, banking, OTPs, or suspicious calls/SMS, immediately include a prominent warning: "Never share your PIN, OTP, or passwords with anyone, even if they say they work at the bank."
6. Language: If the user asks in Hindi or asks for Hindi, answer completely in natural, respectful Hindi (हिंदी) with Devanagari script.
7. Simplicity: Focus on the single easiest method, not multiple alternatives.
`;

class GeminiService {
  constructor() {
    this.apiKey = localStorage.getItem(GEMINI_CONFIG.storageKey) || "";
  }

  getApiKey() {
    return this.apiKey;
  }

  setApiKey(key) {
    this.apiKey = (key || "").trim();
    if (this.apiKey) {
      localStorage.setItem(GEMINI_CONFIG.storageKey, this.apiKey);
    } else {
      localStorage.removeItem(GEMINI_CONFIG.storageKey);
    }
  }

  hasApiKey() {
    return Boolean(this.apiKey && this.apiKey.length > 10);
  }

  /**
   * Main query method
   */
  async askCompanion(userQuery, lang = "en", history = []) {
    if (this.hasApiKey()) {
      try {
        return await this.callGeminiAPI(userQuery, lang, history);
      } catch (err) {
        console.error("Gemini API call failed, falling back to knowledge base:", err);
        return this.getOfflineKnowledge(userQuery, lang);
      }
    } else {
      // Return instant knowledge base guidance
      return this.getOfflineKnowledge(userQuery, lang);
    }
  }

  /**
   * Call Gemini 2.5 Flash via REST API
   */
  async callGeminiAPI(userQuery, lang = "en", history = []) {
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_CONFIG.model}:generateContent?key=${encodeURIComponent(this.apiKey)}`;

    const langDirective = lang === "hi"
      ? "Respond entirely in respectful Hindi (हिंदी) using simple words and clear numbered steps."
      : "Respond in simple, friendly English using numbered steps.";

    const contents = [
      {
        role: "user",
        parts: [
          {
            text: `${SENIOR_SYSTEM_PROMPT}\n\nLanguage requirement: ${langDirective}\n\nUser Question: ${userQuery}`
          }
        ]
      }
    ];

    const response = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: contents,
        generationConfig: {
          temperature: 0.4,
          maxOutputTokens: 1000,
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(`API Error ${response.status}: ${errorData?.error?.message || response.statusText}`);
    }

    const data = await response.json();
    const candidate = data.candidates?.[0];
    const text = candidate?.content?.parts?.[0]?.text;

    if (!text) {
      throw new Error("No response generated by model");
    }

    return {
      text: text,
      source: "gemini",
      isLive: true
    };
  }

  /**
   * Comprehensive offline knowledge base for senior queries
   */
  getOfflineKnowledge(query, lang = "en") {
    const q = (query || "").toLowerCase();

    // 1. Wi-Fi / Internet
    if (q.includes("wifi") || q.includes("wi-fi") || q.includes("internet") || q.includes("वाईफाई") || q.includes("इंटरनेट")) {
      if (lang === "hi") {
        return {
          text: `यहाँ आपके वाई-फाई को ठीक करने का सरल तरीका है:\n\n` +
            `1. **दीवार का स्विच देखें:** अपने काले रंग के वाई-फाई बॉक्स (राउटर) के पास जाएं और देखें कि दीवार का स्विच ऑन है या नहीं।\n\n` +
            `2. **30 सेकंड के लिए बंद करें:** दीवार का स्विच बंद (OFF) करें। मन में 1 से 30 तक गिनें।\n\n` +
            `3. **दोबारा चालू करें:** 30 सेकंड बाद स्विच वापस ऑन (ON) करें।\n\n` +
            `4. **हरी लाइट का इंतज़ार करें:** 2 मिनट प्रतीक्षा करें जब तक कि छोटी हरी या नीली लाइट स्थिर न हो जाए।\n\n` +
            `👁️ **अपनी स्क्रीन पर देखें:** फोन की स्क्रीन को ऊपर से नीचे खींचें और वाई-फाई के गोल नीले निशान को बंद करके 5 सेकंड बाद फिर चालू करें।`,
          source: "offline"
        };
      }
      return {
        text: `Here is the easiest way to fix your home Wi-Fi:\n\n` +
          `1. **Check the Wall Switch:** Walk over to your Wi-Fi box (router) and ensure the wall power switch is turned ON.\n\n` +
          `2. **Turn it OFF for 30 seconds:** Turn the wall power switch OFF. Count slowly to 30.\n\n` +
          `3. **Turn it back ON:** Switch the wall power back ON. Do not press any tiny reset buttons on the back.\n\n` +
          `4. **Wait 2 minutes:** Give the box two minutes to connect. The green or blue light will become steady.\n\n` +
          `👁️ **Look on your phone:** Swipe down from the top of your phone screen, tap the Wi-Fi fan icon to turn it off, wait 5 seconds, and tap it back on.`,
        source: "offline"
      };
    }

    // 2. Flight booking
    if (q.includes("flight") || q.includes("ticket") || q.includes("plane") || q.includes("हवाई") || q.includes("उड़ान") || q.includes("फ्लाइट")) {
      if (lang === "hi") {
        return {
          text: `वरिष्ठ नागरिकों के लिए आसान फ्लाइट बुकिंग चरण:\n\n` +
            `1. **विश्वसनीय वेबसाइट चुनें:** MakeMyTrip, IndiGo, या Air India की आधिकारिक वेबसाइट या ऐप खोलें।\n\n` +
            `2. **वरिष्ठ नागरिक छूट चुनें:** यात्री जोड़ते समय 'Senior Citizen Concession' वाले बॉक्स पर सही का निशान लगाएं। इसमें 60 वर्ष से ऊपर 6% से 10% की छूट मिलती है।\n\n` +
            `3. **व्हीलचेयर की मांग करें:** बुकिंग के दौरान 'Special Assistance' या 'Wheelchair' चुनें। यह सुविधा पूरी तरह निःशुल्क होती है।\n\n` +
            `4. **सीट का चुनाव:** आगे की पंक्ति (2 से 7) में गलियारे (Aisle) वाली सीट चुनें ताकि उठना-बैठना आसान हो।\n\n` +
            `🔒 **सुरक्षा नियम:** हवाई अड्डे पर अपना आधार कार्ड या सीनियर सिटिजन आईडी कार्ड अवश्य साथ रखें।`,
          source: "offline"
        };
      }
      return {
        text: `Simple steps to book a flight comfortably as a senior:\n\n` +
          `1. **Choose a direct airline:** Open MakeMyTrip, IndiGo, or Air India on your computer or phone.\n\n` +
          `2. **Select Senior Citizen Fare:** Look for the checkbox labeled "Senior Citizen" before searching. Travelers aged 60+ get up to 6% to 10% off the base fare.\n\n` +
          `3. **Request Free Wheelchair:** Under Special Assistance, select "Wheelchair assistance". Airline staff will escort you right to the aircraft door.\n\n` +
          `4. **Choose an Aisle Seat:** Pick an aisle seat in rows 2 to 7 near the front for easy walking to the washroom.\n\n` +
          `🔒 **Safety Note:** Keep all your daily medicines in your hand luggage, never in checked baggage. Carry your Aadhaar or Senior Citizen ID card.`,
        source: "offline"
      };
    }

    // 3. WhatsApp Video Call
    if (q.includes("whatsapp") || q.includes("video call") || q.includes("व्हाट्सएप") || q.includes("वीडियो कॉल")) {
      if (lang === "hi") {
        return {
          text: `व्हाट्सएप पर वीडियो कॉल करने का तरीका:\n\n` +
            `1. **व्हाट्सएप खोलें:** अपनी स्क्रीन पर हरे रंग का गोल निशान दबाएं जिस पर सफेद फोन बना है।\n\n` +
            `2. **परिवार के सदस्य का नाम खोजें:** अपनी चैट सूची में उस व्यक्ति के नाम पर टच करें जिसे आप कॉल करना चाहते हैं।\n\n` +
            `3. **वीडियो कैमरा का निशान दबाएं:** ऊपर दाईं ओर एक छोटा वीडियो कैमरा (📹) बना होगा। उस पर उंगली से टच करें।\n\n` +
            `4. **कॉल शुरू हो जाएगी:** फोन को अपने चेहरे के सामने रखें और बातचीत का आनंद लें! जब बात खत्म हो जाए, तो लाल रंग का गोल बटन दबाएं।`,
          source: "offline"
        };
      }
      return {
        text: `How to make a WhatsApp Video Call to family:\n\n` +
          `1. **Open WhatsApp:** Tap the bright green circle with a white telephone handset inside.\n\n` +
          `2. **Tap their Name:** Tap on the name of your child or grandchild in your chat list.\n\n` +
          `3. **Tap the Video Camera:** Look at the top right corner of the screen. Tap the small video camera icon (📹).\n\n` +
          `4. **Hold phone up:** Hold the phone at eye level so they can see your smiling face! When finished, tap the round red button to end call.`,
        source: "offline"
      };
    }

    // 4. Scam / Suspicious message
    if (q.includes("scam") || q.includes("otp") || q.includes("bank") || q.includes("electricity") || q.includes("धोखा") || q.includes("ओटीपी")) {
      if (lang === "hi") {
        return {
          text: `⚠️ **सावधानी: यह धोखाधड़ी का प्रयास हो सकता है!**\n\n` +
            `1. **ओटीपी या पासवर्ड कभी न बताएं:** बैंक अधिकारी या पुलिस कभी भी आपसे ओटीपी, पिन या पासवर्ड नहीं मांगते।\n\n` +
            `2. **किसी अनजान लिंक पर टच न करें:** संदेश में आए नीले लिंक या नंबर पर कॉल न करें।\n\n` +
            `3. **AnyDesk / TeamViewer डाउनलोड न करें:** कोई भी कहे कि ऐप डाउनलोड करो, तो तुरंत फोन काट दें।\n\n` +
            `📞 **मदद के लिए:** तुरंत राष्ट्रीय साइबर हेल्पलाइन **1930** पर कॉल करें। यह पूर्णतः सुरक्षित और सरकारी है।`,
          source: "offline"
        };
      }
      return {
        text: `⚠️ **CAUTION: This looks like a potential scam!**\n\n` +
          `1. **Never share OTP or PIN:** No real bank, electric company, or police officer will ever ask for your 4 or 6-digit OTP or password.\n\n` +
          `2. **Do not click blue links:** Never click links in SMS or WhatsApp claiming your electricity will be disconnected or lottery won.\n\n` +
          `3. **Never install screen-sharing apps:** If someone tells you to download "AnyDesk", "TeamViewer", or "RustDesk", hang up immediately!\n\n` +
          `📞 **Helpline:** Call the National Cybercrime Helpline at **1930** immediately to report fraud or freeze unauthorized transactions.`,
        source: "offline"
      };
    }

    // Default general response
    if (lang === "hi") {
      return {
        text: `नमस्ते! मैं आपका वरिष्ठ दैनिक सहायक हूँ।\n\n` +
          `मैं आपकी हर रोज़मर्रा की ज़रूरत में मदद कर सकता हूँ — जैसे कि वाई-फाई ठीक करना, हवाई टिकट बुक करना, दवाइयों का हिसाब रखना, या व्हाट्सएप पर बच्चों से बात करना।\n\n` +
          `आप ऊपर दिए गए किसी भी बड़े बटन को दबा सकते हैं, या जो पूछना चाहते हैं बोलकर या लिखकर पूछ सकते हैं। मैं बहुत धैर्य से एक-एक कदम समझाऊंगा।`,
        source: "offline"
      };
    }

    return {
      text: `Hello! I am your Senior Daily Companion.\n\n` +
        `I am here to help you step-by-step with anything you need — whether it's fixing your Wi-Fi, booking a flight with senior discounts, checking if an SMS is safe, or tracking your daily medicines.\n\n` +
        `You can tap any of the large tiles above, or ask me any question using your voice or typing. I will explain everything slowly and clearly!`,
      source: "offline"
    };
  }
}

window.GeminiService = new GeminiService();
